### ISSUE TITLE
Incompatibility with Cocoapods >= 1.0

### ISSUE THREAD

**Issue by belkevich** [Smartling/ios-i18n#28]
Hello,

Some of my private pods use `Smartling`. And them stop working after update of cocoapods to 1.0.1. I'm unable to push podspec. It didn't pass the validation. The error is:
```bash
xcodebuild:  Smartling.i18n/Smartling.i18n/SmartlingLib.h:32:9: fatal error: 'SmartlingLib/SLLocalization.h' file not found
```

So, I've tried to validate `Smartling` podspec with cocoapods 1.0.1. And it fails.
```bash
pod spec lint https://raw.githubusercontent.com/Smartling/ios-i18n/master/Smartling.i18n.podspec

 -> Smartling.i18n (1.0.11)
    - ERROR | xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | xcodebuild:  /Users/alex/Library/Developer/Xcode/DerivedData/App-diyqsuoeckugulbyqokvsklkqffn/Build/Products/Release-iphonesimulator/Smartling.i18n/Smartling_i18n.framework/Headers/SmartlingLib.h:32:9: fatal error: 'SmartlingLib/SLLocalization.h' file not found
    - NOTE  | xcodebuild:  /var/folders/t0/tq3q_d5x2874hby2xtwswzjw0000gn/T/CocoaPods/Lint/App/main.m:3:9: fatal error: could not build module 'Smartling_i18n'
    - NOTE  | [OSX] xcodebuild:  /Users/alex/Library/Developer/Xcode/DerivedData/App-diyqsuoeckugulbyqokvsklkqffn/Build/Products/Release/Smartling.i18n/Smartling_i18n.framework/Headers/SmartlingLib.h:21:9: fatal error: 'UIKit/UIKit.h' file not found

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error.
```

I think it's related to 'dot' in library name. But I'm not sure.

**Comment by belkevich** [comment]
I've fixed it. Please, check out the [pull request](https://github.com/Smartling/ios-i18n/pull/29)

**Comment by jackrmomo** [comment]
[]()
